// code_vue/src/components/Grid.vue
<script setup>
import { useGridStore } from '../stores/grid.js'

const gridStore = useGridStore()
gridStore.initGrid()


function getCellStyle(value) {
  if (value === null) return { backgroundColor: 'inherit' }	
    
  const hue = 30 + value * 20 % 360

  return {
    backgroundColor: `hsl(${hue}, 90%, 60%)`,
    color: 'black',
    transform: 'scale(1.0)',
  }
}

</script>

<template>
  <!-- TOP ROW -->
  <div class="w-full flex justify-between items-center p-4">
    <img src="../assets/vue.svg" alt="Vue logo" class="h-8 w-auto" />
    <h1 style="font-family: 'Courier New', Courier, monospace;">BLOCKENSPIEL</h1>
    <button
      class="dark:bg-purple-600 dark:hover:bg-purple-700
         bg-purple-800 hover:bg-purple-900 text-white font-bold py-2 px-4 rounded"
      @click="gridStore.resetGrid()"
    >
        Reset gridd
    </button>
  </div>

  <!-- GRID -->
  <div class="flex flex-col mt-4 min-w-full min-h-full">
    <div
      v-for="(row, rowIndex) in gridStore.grid"
      :key="rowIndex"
      class="flex"
    >
      <button
        v-for="(cell, colIndex) in row"
        :key="colIndex"
        role="button"
        class="w-6 h-6 flex items-center justify-center text-s font-bold transition-all 
          duration-300 cursor-pointer border-2 border-gray-300 dark:border-gray-600 transition-colors"
        :style="getCellStyle(cell)"
        @click="gridStore.updateGrid(rowIndex, colIndex)"
      >
        {{ cell }}
      </button>
    </div>
  </div>
</template>


<style scoped>
</style>

// code_react/src/components/Grid.jsx
import { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux'
import { initGrid, updateGrid, resetGrid } from '../store/grid';
import reactLogo from '../assets/react.svg'

export default function Grid() {

  const dispatch = useDispatch();

  const grid = useSelector((state) => state.grid.grid);
  const rows = useSelector((state) => state.grid.rows);
  const cols = useSelector((state) => state.grid.cols);


  useEffect(() => {
    dispatch(initGrid());
  }, [dispatch]);

  const getCellStyle = (value) => {
    if (value === null) return { backgroundColor: 'inherit' };

    const hue = (30 + (value * 20)) % 360;
    return {
      backgroundColor: `hsl(${hue}, 90%, 60%)`,
      color: 'black',
      transform: 'scale(1.0)',
    };
  };

  return (
    <div className="min-w-full min-h-full p-4">
      {/* TOP ROW */}
      <div className="w-full flex justify-between items-center p-4">
        <img src={reactLogo} alt="React logo" className="h-8 w-auto" />
        <h1 style={{ fontFamily: "'Courier New', Courier, monospace" }}>BLOCKENSPIEL</h1>
        <button
          className="dark:bg-purple-600 dark:hover:bg-purple-700
                  bg-purple-800 hover:bg-purple-900 text-white font-bold py-2 px-4 rounded"
          onClick={() => dispatch(resetGrid())}
        >
          Reset grid
        </button>
      </div>

      {/* GRID */}
      <div className="flex flex-col">
        {grid.map((row, rowIndex) => (
          <div key={rowIndex} className="flex">
            {row.map((cell, colIndex) => (
              <div
                key={colIndex}
                style={getCellStyle(cell)}
                className="w-6 h-6 flex items-center justify-center text-s font-bold
                           transition-all duration-300 cursor-pointer border-2 border-gray-300 dark:border-gray-600 transition-colors"
                onClick={() => dispatch(updateGrid({ row: rowIndex, col: colIndex }))}
              >
                {cell !== null ? cell : ''}
              </div>
            ))}
          </div>
        ))}
      </div>
    </div >
  );
}
